### ISSUE TITLE
1.21 Port already exists with significant performance issues. Does this port fix that?

### ISSUE THREAD

**Issue by BreadBxsket** [wenwen357951/placeable-fabric#1]
The port exists [here (modrinth)](https://modrinth.com/datapack/placeable), and [here (curseforge)](https://www.curseforge.com/minecraft/texture-packs/placeable-data-packhttps://www.curseforge.com/minecraft/texture-packs/placeable-data-pack). However, that author offers no method of contact. I'm curious if this port fixes the performance problems as I'd still love to use this. Attached is a debug profiling from my co-op server.

[profiling.txt](https://github.com/user-attachments/files/16356154/profiling.txt)

**Comment by wenwen357951** [comment]
Hello, thank you for providing the performance data.

I have checked and found that the mod is implemented by wrapping datapacks, which can indeed cause some performance issues. 

My fork is implemented using the Fabric API, which can address the performance issues.

**Comment by BreadBxsket** [comment]
Added it today and it performs perfectly well, thanks for the port I appreciate it!
